run:
  timeout: 10m
linters-settings:
  nestif:
    min-complexity: 72
linters:
  fast: true
  enable-all: true
  disable:
    - depguard
    - dupl
    - funlen
    - gocognit
    - goconst
    - gocyclo
    - gomnd
    - ifshort
    - interfacebloat
    - maintidx
    - nosnakecase
    - scopelint
    - tagliatelle
    - testpackage
