project_name: circonus-cma

builds: 
  - id: cma
    main: ./cmd/circonus-cma
    binary: sbin/circonus-cma
    env: 
      - CGO_ENABLED=0
    goarch: 
      - amd64
      - arm64
    goos: 
      - linux
      - darwin
      - windows
    ignore: 
      - goarch: 386
      - goos: windows
        goarch: arm64
    ldflags: 
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.VERSION={{.Version}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.COMMIT={{.ShortCommit}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.DATE={{.Date}}
      - -X github.com/circonus-labs/circonus-kubernetes-agent/internal/release.TAG={{.Tag}}

# dockers:
#   - id: cma-amd64
#     goos: linux
#     goarch: amd64
#     goarm: ''
#     ids: ['cma']
#     image_templates:
#       - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
#       - "circonus/{{.ProjectName}}:latest-amd64"
#     skip_push: false
#     dockerfile: builds/docker/x86_64/Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--platform=linux/amd64"
#     extra_files:
#       - etc/circonus-cma.yaml

#   - id: ea-arm64
#     goos: linux
#     goarch: arm64
#     goarm: ''
#     ids: ['ea']
#     image_templates:
#       - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
#       - "circonus/{{.ProjectName}}:latest-arm64"
#     skip_push: false
#     dockerfile: builds/docker/arm64/Dockerfile
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.label-schema.schema-version=1.0"
#       - "--label=org.label-schema.version={{.Version}}"
#       - "--label=org.label-schema.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--platform=linux/arm64"
#     extra_files:
#       - etc/circonus-cma.yaml

# docker_manifests:
#   - name_template: "circonus/{{.ProjectName}}:latest"
#     image_templates:
#       - "circonus/{{.ProjectName}}:latest-amd64"
#       - "circonus/{{.ProjectName}}:latest-arm64"
#   - name_template: "circonus/{{.ProjectName}}:{{.Tag}}"
#     image_templates:
#       - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
#       - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"

nfpms:
  - vendor: Circonus, Inc.
    homepage: https://circonus.com
    maintainer: Circonus <support@circonus.com>
    description: Circonus Collector Management Agent
    license: MIT
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    bindir: /opt/circonus/cma
    contents:
      - src: "LICENSE"
        dst: "/opt/circonus/cma/LICENSE"
      - src: "README.md"
        dst: "/opt/circonus/cma/README.md"
      - src: "CHANGELOG.md"
        dst: "/opt/circonus/cma/CHANGELOG.md"
      - src: "service/circonus-cma.linux.service"
        dst: "/opt/circonus/cma/service/circonus-cma.service"
      - src: "service/circonus-cma.linux.init"
        dst: "/opt/circonus/cma/service/circonus-cma.init"
      - src: "etc/circonus-cma.yaml" 
        dst: "/opt/circonus/cma/etc/circonus-cma.yaml"
        type: "config|noreplace"
    overrides:
      deb:
        scripts:
          preinstall: "builds/deb/pre-install.sh"
          postinstall: "builds/deb/post-install.sh"
          preremove: "builds/deb/pre-remove.sh"
          postremove: "builds/deb/post-remove.sh"
      rpm:
        scripts:
          preinstall: "builds/rpm/pre-install.sh"
          postinstall: "builds/rpm/post-install.sh"
          postremove: "builds/rpm/post-remove.sh"

archives:
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - etc/circonus-cma.yaml
      - service/*

release:
  github:
      owner: circonus
      name: collector-management-agent
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: desc
  abbrev: 0
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Dependencies'
      regexp: "^.*build(deps):+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"
