project_name: circonus-am

builds: 
  - id: am
    main: ./cmd/circonus-am
    binary: sbin/circonus-am
    env: 
      - CGO_ENABLED=0
    goarch: 
      - amd64
      - arm64
    goos: 
      - linux
      # - windows
    ignore: 
      - goarch: 386
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags: 
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/circonus/agent-manager/internal/release.VERSION={{.Version}}
      - -X github.com/circonus/agent-manager/internal/release.COMMIT={{.ShortCommit}}
      - -X github.com/circonus/agent-manager/internal/release.DATE={{.Date}}
      - -X github.com/circonus/agent-manager/internal/release.TAG={{.Tag}}

  - id: am-macos_amd64
    main: ./cmd/circonus-am
    binary: sbin/circonus-am
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/circonus/agent-manager/internal/release.VERSION={{.Version}}
      - -X github.com/circonus/agent-manager/internal/release.COMMIT={{.ShortCommit}}
      - -X github.com/circonus/agent-manager/internal/release.DATE={{.Date}}
      - -X github.com/circonus/agent-manager/internal/release.TAG={{.Tag}}
    hooks:
      post: ./macos_sign.sh {{ .Path }}

  - id: am-macos_arm64
    main: ./cmd/circonus-am
    binary: sbin/circonus-am
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -extldflags "-static"
      - -X github.com/circonus/agent-manager/internal/release.VERSION={{.Version}}
      - -X github.com/circonus/agent-manager/internal/release.COMMIT={{.ShortCommit}}
      - -X github.com/circonus/agent-manager/internal/release.DATE={{.Date}}
      - -X github.com/circonus/agent-manager/internal/release.TAG={{.Tag}}
    hooks:
      post: ./macos_sign.sh {{ .Path }}

universal_binaries:
  - id: macos_universal
    ids:
      - am-macos_amd64
      - am-macos_arm64
    name_template: sbin/circonus-am
    replace: false
    hooks:
      post: ./macos_sign.sh {{ .Path }}

brews:
  - repository:
      owner: circonus
      name: homebrew-circonus-agent-manager
    folder: Formula
    goarm: "7"
    homepage: https://circonus.com
    description: Circonus Agent Manager
    license: MIT
    caveats: |
      Install:
      1. Run #{sbin}/circonus-am --register="registration token"
      2. Run "brew services start circonus-am"

      Upgrade:
      1. Run "brew services restart circonus-am"

    test: |
      system "#{sbin}/circonus-am --version"

    install: |
      sbin.install "sbin/circonus-am"
      pkgetc.install "etc/circonus-am.yaml" => "circonus-am.yaml"
      doc.install "README.md", "LICENSE"

    service: |
      run [opt_sbin/"circonus-am", "--config", etc/"circonus-am/circonus-am.yaml"]
      keep_alive true
      log_path var/"log/circonus-agent-manager.log"
      error_log_path var/"log/circonus-agent-manager.log"

nfpms:
  - id: cam
    vendor: Circonus, Inc.
    homepage: https://circonus.com
    maintainer: Circonus <support@circonus.com>
    description: Circonus Agent Manager
    license: BSD-3-Clause
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    bindir: /opt/circonus/am
    contents:
      - src: "LICENSE"
        dst: "/opt/circonus/am/LICENSE"
      - src: "README.md"
        dst: "/opt/circonus/am/README.md"
      - src: "CHANGELOG.md"
        dst: "/opt/circonus/am/CHANGELOG.md"
      - src: "service/circonus-am.linux.service"
        dst: "/opt/circonus/am/service/circonus-am.service"
      - src: "service/circonus-am.linux.init"
        dst: "/opt/circonus/am/service/circonus-am.init"
      - src: "etc/circonus-am.yaml" 
        dst: "/opt/circonus/am/etc/circonus-am.yaml"
        type: "config|noreplace"
    rpm:
      signature:
        key_file: "{{ .Env.GPG_RPM_KEY_PATH }}"
    overrides:
      deb:
        scripts:
          preinstall: "builds/deb/pre-install.sh"
          postinstall: "builds/deb/post-install.sh"
          preremove: "builds/deb/pre-remove.sh"
          postremove: "builds/deb/post-remove.sh"
      rpm:
        scripts:
          preinstall: "builds/rpm/pre-install.sh"
          postinstall: "builds/rpm/post-install.sh"
          postremove: "builds/rpm/post-remove.sh"

dockers:
  - id: am-amd64
    goos: linux
    goarch: amd64
    goarm: ''
    ids: ['am']
    image_templates:
      - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
      - "circonus/{{.ProjectName}}:latest-amd64"
    skip_push: false
    dockerfile: builds/docker/x86_64/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - etc/circonus-am.yaml

  - id: am-arm64
    goos: linux
    goarch: arm64
    goarm: ''
    ids: ['am']
    image_templates:
      - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"
      - "circonus/{{.ProjectName}}:latest-arm64"
    skip_push: false
    dockerfile: builds/docker/arm64/Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.label-schema.schema-version=1.0"
      - "--label=org.label-schema.version={{.Version}}"
      - "--label=org.label-schema.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    extra_files:
      - etc/circonus-am.yaml

docker_manifests:
  - name_template: "circonus/{{.ProjectName}}:latest"
    image_templates:
      - "circonus/{{.ProjectName}}:latest-amd64"
      - "circonus/{{.ProjectName}}:latest-arm64"
  - name_template: "circonus/{{.ProjectName}}:{{.Tag}}"
    image_templates:
      - "circonus/{{.ProjectName}}:{{.Tag}}-amd64"
      - "circonus/{{.ProjectName}}:{{.Tag}}-arm64"

archives:
  - id: default
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
      - etc/circonus-am.yaml
      - service/*

release:
  github:
      owner: circonus
      name: agent-manager
  draft: false
  prerelease: auto

changelog:
  use: git
  sort: desc
  abbrev: 0
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Dependencies'
      regexp: "^.*build(deps):+.*$"
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs:'
      - typo

checksum:
  name_template: "{{.ProjectName}}_checksums.txt"
