name: codecov
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - uses: codecov/codecov-action@v4
        if: success() || failure()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          files: ./coverage.out
