name: golangci-lint
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v4.0.0
        with:
          args: --timeout=5m
