name: govulncheck
on:
  push:
    tags: [ "v*" ]
    branches: [ main ]
  pull_request:
    branches: [ "*" ]
jobs:
  govulncheck:
    name: govulncheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go install golang.org/x/vuln/cmd/govulncheck@latest
      - run: govulncheck ./...
