name: vuln_check
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
jobs:
  govulncheck:
    name: vulncheck
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          cache: true
          check-latest: true
          go-version: '>=1.20.6'

      - name: Install govulncheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Run govulncheck
        run: govulncheck ./...
